In [1]:
import numpy as np

In [2]:
a = [1,2,3,4,5]
b = [5,4,3,2,1]

In [3]:
a = np.array(a,int)
a

array([1, 2, 3, 4, 5])

In [6]:
test_arry = np.array(['1', 2, 5.0, 4], float)
test_arry

array([1., 2., 5., 4.])

In [9]:
print(type(test_arry))
print(type(test_arry[3]))

<class 'numpy.ndarray'>
<class 'numpy.float64'>


In [13]:
tensor = [
        [[1,2,3,4],
        [1,2,3,4],
        [1,2,3,4]],

        [[1,2,3,4],
        [1,2,3,4],
        [1,2,3,4]],

        [[1,2,3,4],
        [1,2,3,4],
        [1,2,3,4]],

        [[1,2,3,4],
        [1,2,3,4],
        [1,2,3,4]]
]
print(np.array(tensor, int).shape) # shape
print(np.array(tensor, int).ndim) # 차원의 개수
print(np.array(tensor, int).size) # 데이터의 개수

(4, 3, 4)
3
48


# reshape

In [15]:
test_matrix = [[1,2,3,4], [1,2,5,8]]
np.array(test_matrix).shape

(2, 4)

In [16]:
np.array(test_matrix).reshape(4,2)

array([[1, 2],
       [3, 4],
       [1, 2],
       [5, 8]])

In [17]:
np.array(test_matrix).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [18]:
np.array(test_matrix).reshape(8,)

array([1, 2, 3, 4, 1, 2, 5, 8])

In [19]:
np.array(test_matrix).reshape(-1,2) # -1: 알아서 잡아 줌

array([[1, 2],
       [3, 4],
       [1, 2],
       [5, 8]])

# flatten
다차원 array를 1차원 array로 변환

In [20]:
test_matrix = [[[1,2,3,4], [1,2,5,8]], [[1,2,3,4], [1,2,5,8]]]
np.array(test_matrix)

array([[[1, 2, 3, 4],
        [1, 2, 5, 8]],

       [[1, 2, 3, 4],
        [1, 2, 5, 8]]])

In [21]:
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 1, 2, 5, 8, 1, 2, 3, 4, 1, 2, 5, 8])

In [22]:
np.array(test_matrix).flatten().shape

(16,)

# indexing

리스트와 달리 [r,c] 표기법 가능

In [23]:
tm = np.array([[1,2,3],[4.5,5,6]], int)
tm

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
print(tm[0][2])
print(tm[0, 2])

3
3


In [27]:
tm[0,0] = 10
tm

array([[10,  2,  3],
       [ 4,  5,  6]])

# slicing

list와 달리 행과 열 부분을 나눠서 slicing 가능

In [28]:
tm = np.array([[1,2,5,8], [1,2,5,8], [1,2,5,8], [1,2,5,8]], int)
tm

array([[1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8]])

In [29]:
tm[:, 2:]

array([[5, 8],
       [5, 8],
       [5, 8],
       [5, 8]])

In [30]:
tm[1:2, :2]

array([[1, 2]])

In [32]:
tm = np.array([[1,2,3,4,5], [6,7,8,9,10]], int)
tm

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [33]:
tm[1]

array([ 6,  7,  8,  9, 10])

In [34]:
tm[1:3]

array([[ 6,  7,  8,  9, 10]])

In [35]:
a = np.arange(100).reshape(10,10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [36]:
a[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

# creation function

In [37]:
tm = [
    [[1,2,3,4],
     [5,6,7,8],
     [9,10,11,12]],
      
    [[1,2,3,4],
     [5,6,7,8],
     [9,10,11,12]],
      
    [[1,2,3,4],
     [5,6,7,8],
     [9,10,11,12]],
      
]

In [39]:
np.array(tm).sum(axis = 2) # 행을 더해 줌

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])

In [40]:
np.array(tm).sum(axis = 1) # 열을 더해줌

array([[15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24]])

In [41]:
np.array(tm).sum(axis = 0) # 같은 위치 채널 값 더해줌

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

# concatenate

In [42]:
a = np.array([[1,2], [3,4]])
b = np.array([[5], [6]])
np.concatenate((a,b), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [43]:
a = np.array([[1,2], [3,4]])
b = np.array([5,6]) # 지금은 벡터임
b = b[np.newaxis, :] # 축 추가 -> 행열이 됨
np.concatenate((a,b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

# comparisons

In [44]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
a < 4 # broadcasting이 일어남 -> 각각의 element에 적용

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [46]:
np.any(a>5), np.all(a>5) # 하나라도 True면 True, 전부 True여야 True

(True, False)

In [47]:
# 배열의 크기가 같으면 element간 비교 결과를 Boolean type으로 반환
a = np.array([1,3,0], float)
b = np.array([5,2,1], float)
a > b

array([False,  True, False])

# np.where

In [48]:
a = np.array([1,3,0], float)
a

array([1., 3., 0.])

In [49]:
np.where(a > 5)

(array([], dtype=int64),)

In [50]:
np.where(a > 2) # tuple 값으로 반환

(array([1]),)

In [51]:
np.where(a < 3, 3,2) # where(condition, True, False) : condition에 대해 True면 True 위치의 값을, False면 False 위치의 값을 대입

array([3, 2, 3])

# argmax & argmin

idx를 반환해 줌

In [52]:
a = np.array([1,2,4,5,8,78,23,3])
a

array([ 1,  2,  4,  5,  8, 78, 23,  3])

In [53]:
a.argsort() # 정렬됬을때 키 값의 순서를 idx로 반환

array([0, 1, 7, 2, 3, 4, 6, 5])

In [55]:
print(np.argmax(a))
print(a[np.argmax(a)])
print()
print(np.argmin(a))
print(a[np.argmin(a)])

5
78

0
1
