<a href="https://colab.research.google.com/github/chaeminsoo/boostcamp_ai_tech_RecSys/blob/main/pytorch_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
n_array = np.arange(10).reshape(2,5)
print(n_array)
print('ndim: ', n_array.ndim, 'shape: ', n_array.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]]
ndim:  2 shape:  (2, 5)


In [3]:
import torch
t_array = torch.FloatTensor(n_array)
print(t_array)
print('ndim: ', t_array.ndim, 'shape: ', t_array.shape)

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])
ndim:  2 shape:  torch.Size([2, 5])


# mm VS dot VS matmul

In [4]:
n1 = np.arange(10).reshape(2,5)
t1 = torch.FloatTensor(n1)
n2 = np.arange(10).reshape(5,2)
t2 = torch.FloatTensor(n2)
print(t1)
print()
print(t2)

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])

tensor([[0., 1.],
        [2., 3.],
        [4., 5.],
        [6., 7.],
        [8., 9.]])


In [5]:
t1.mm(t2) # 행열 곱

tensor([[ 60.,  70.],
        [160., 195.]])

In [7]:
t1.dot(t2) # 벡터 곱을 위한 것

RuntimeError: ignored

In [11]:
 a = torch.rand(5,2,3)
 b = torch.rand(5)
 c = torch.rand(3)
 print(a)
 print()
 print(b)
 print()
 print(c)

tensor([[[0.7172, 0.0113, 0.1756],
         [0.3797, 0.2624, 0.6796]],

        [[0.4680, 0.8949, 0.0726],
         [0.5870, 0.8048, 0.4351]],

        [[0.9841, 0.4128, 0.6443],
         [0.4883, 0.0132, 0.6298]],

        [[0.1708, 0.8437, 0.7702],
         [0.1939, 0.9117, 0.3442]],

        [[0.0350, 0.0788, 0.6781],
         [0.5681, 0.1784, 0.3320]]])

tensor([0.7493, 0.0028, 0.0879, 0.6992, 0.2594])

tensor([0.1565, 0.6318, 0.1303])


In [9]:
a.mm(b) # 벡터가 들어온 상황에서 broadcating을 지원하지 않기 때문에 Error 발생

RuntimeError: ignored

In [12]:
a.mm(c) # 벡터가 들어온 상황에서 broadcating을 지원하지 않기 때문에 Error 발생

RuntimeError: ignored

In [10]:
a.matmul(b) # 이건 사이즈가 안 맞아서 Error

RuntimeError: ignored

In [13]:
a.matmul(c) # 벡터가 들어온 상황에서 broadcating을 지원하기 때문에 Error 발생하지 않음

tensor([[0.1422, 0.3138],
        [0.6481, 0.6570],
        [0.4988, 0.1668],
        [0.6602, 0.6512],
        [0.1436, 0.2449]])

# AutoGrad

In [18]:
w = torch.tensor(2.0, requires_grad = True)
y = w**2
z = 10*y +25
z.backward() # 미분해줌 
w.grad # 20*w (w = 2로 위에서 설정해 줬음)

tensor(40.)

In [19]:
# 편미분
a = torch.tensor([2., 3.,], requires_grad=True)
b = torch.tensor([6., 4.,], requires_grad=True)
Q = 3*a**3 - b**2
external_grad = torch.tensor([1., 1.,]) # 미분하는 값이 2개기 때문에 크기를 잡아준 것
Q.backward(external_grad)

a.grad # 미분했을 때의 값

tensor([36., 81.])

In [20]:
b.grad

tensor([-12.,  -8.])